In [10]:
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
from google.colab import files
upload=files.upload()

Saving Heart.csv to Heart (1).csv

In [12]:
df=pd.read_csv('Heart.csv')
df.head()

   age  gender  family  diet  lifestyle  chol  heartdisease
0   52       1       0   125        212     0             1
1   53       1       0   140        203     1             0
2   70       1       0   145        174     0             1
3   61       1       0   148        203     0             1
4   62       0       0   138        294     1             1

In [13]:
df.shape

(1025, 7)

In [14]:
df.isnull().sum()

age             0
gender          0
family          0
diet            0
lifestyle       0
chol            0
heartdisease    0
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           1025 non-null   int64
 1   gender        1025 non-null   int64
 2   family        1025 non-null   int64
 3   diet          1025 non-null   int64
 4   lifestyle     1025 non-null   int64
 5   chol          1025 non-null   int64
 6   heartdisease  1025 non-null   int64
dtypes: int64(7)
memory usage: 56.2 KB

In [16]:
df.describe()

,age,gender,family,diet,lifestyle,chol,heartdisease
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000

In [17]:
df.columns

Index(['age', 'gender', 'family', 'diet', 'lifestyle', 'chol', 'heartdisease'], dtype='object')

In [18]:
!pip install pgmpy==1.0.0

Requirement already satisfied: pgmpy==1.0.0 in /usr/local/lib/python3.13/dist-packages (1.0.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.2.3)
Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.11.0+cpu)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (0.14.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (4.67.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.5.3)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.4.0)
Requirement already satisfied: pyro-ppl in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2026.3)
Requirement already satisfied: pyro-api>=0.1.1 in /usr/local/lib/python3.13/dist-packages (from pyro-ppl->pgmpy==1.0.0) (0.1.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.32.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (2025.3.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->pgmpy==1.0.0) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (26.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->pgmpy==1.0.0) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch->pgmpy==1.0.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch->pgmpy==1.0.0) (3.0.3)

In [19]:
import pgmpy
print(pgmpy.__version__)

1.0.0

In [20]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
model = DiscreteBayesianNetwork([
    ('age', 'target'),
    ('sex', 'target'),
    ('cp', 'target'),
    ('chol', 'target'),
    ('fbs', 'target'),
    ('restecg', 'target')
])

mle = MaximumLikelihoodEstimator(model, df)
cpds = mle.get_parameters()
model.add_cpds(*cpds)
print(model.get_cpds('target'))

KeyError: 'cp'

In [ ]:
print(model.get_cpds('age'))

In [ ]:
print(model.get_cpds('sex'))

In [ ]:
print(model.get_cpds('chol'))